services:
  talos-agent:
    build: .
    # NOTE: Run ./scripts/build_and_push_container_image.sh to retrieve the digest.
    image: ghcr.io/talos-agent/talos:latest-agent@sha256:a10b3f005fdca4462da59f38a7d9e650c72ae91d88666dcac908f8bde30e8d44
    container_name: talos-agent
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
    volumes:
      - talos_data:/app/data
      - /run/rofl-appd.sock:/run/rofl-appd.sock
    ports:
      - "7000:7000"

volumes:
  talos_data:
