services:
  talos-agent:
    build: .
    # NOTE: Run ./scripts/build_and_push_container_image.sh to retrieve the digest.
    image: ghcr.io/talos-agent/talos:latest-agent@sha256:c3cf64387d8604b35649ca5864a8a0973d104bb41f29e1f1578b08f66a4c8f95
    container_name: talos-agent
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
    volumes:
      - talos_data:/app/data
      - /run/rofl-appd.sock:/run/rofl-appd.sock
    ports:
      - "7011:8000"

volumes:
  talos_data:
