services:
  talos-agent:
    build: .
    # NOTE: Run ./scripts/build_and_push_container_image.sh to retrieve the digest.
    image: ghcr.io/talos-agent/talos:latest-agent@sha256:c4905422ffb4768320b053a598cfc3a033ac86d406aac8a82684d8d28729f857
    container_name: talos-agent
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///app/data/talos_data.db}
    volumes:
      - talos_data:/app/data
      - /run/rofl-appd.sock:/run/rofl-appd.sock
    ports:
      - "8000:8000"

volumes:
  talos_data:
