services:
  talos-agent:
    build: .
    container_name: talos-agent
    restart: unless-stopped
    ports:
      - "7011:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
      - PINATA_API_KEY=${PINATA_API_KEY}
      - PINATA_SECRET_API_KEY=${PINATA_SECRET_API_KEY}
    volumes:
      - talos_data:/app/data

volumes:
  talos_data:

